version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trustguard
    ports:
      - "3306:3306"
    volumes:
      - mysql_trustguard_data:/var/lib/mysql

volumes:
  mysql_trustguard_data:
